version: "3.9"
services:
  api:
    build: .
    image: langgraph-openai:memory
    env_file:
      - .env
    ports:
      - "8080:${PORT:-8080}"
    restart: unless-stopped
    volumes:
      - ./data:/data
